#!/usr/bin/env python3

import os
import json
from ramda import *

SOURCES = './ramda/'

docs = json.load(open('./jsdocs.json'))
filter_functions = filter(both(test(r'.py$'), complement(test('test'))))
clear_description = replace(r'\.?\n$', '')

for filename in filter_functions(os.listdir(SOURCES)):
    name = replace(r'.py$', '', filename)
    source = open(SOURCES + filename).read()

    func = find(prop_eq('name', name), docs)

    if not func:
        print(f'{name} has no description')
        continue

    doc_string = f'\n    """{clear_description(func["description"])}"""\n'

    modified = if_else(
        test('"""'),
        replace(fr'\n\s+"""(.*\n)*.*"""\n', doc_string),
        replace(fr'(def {name}.*:)\n', rf'\1{doc_string}'),
        source)

    open(SOURCES + filename, 'w').write(modified)
